version: '3'

services:
  db:
    image: mysql:latest
    env_file:
      - .env
    networks:
      - drive
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}

  bot:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    depends_on:
      - db
    networks:
      - drive
    volumes:
      - ./:/app

networks:
  drive:
