version: '3'

services:
  db:
    image: mysql:latest
    env_file:
      - ./env/.env.${NODE_ENV}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - drive
    volumes:
      - mysql-vol:/var/lib/mysql

  bot:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.${NODE_ENV}
    env_file:
      - ./env/.env.${NODE_ENV}
    depends_on:
      - db
    networks:
      - drive
    volumes:
      - ./:/app
    ports:
      - "7000:80"

networks:
  drive:


volumes:
  mysql-vol:
