version: '3'

services:
  db:
    image: mysql:latest
    env_file:
      - .env
    networks:
      - drive
    volumes:
      - mysql-vol:/var/lib/mysql

  bot:
    build:
      context: .
      dockerfile: ./docker/bot.dockerfile
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - drive
    volumes:
      - ./:/app

networks:
  drive:


volumes:
  mysql-vol:
