version: '3'

services:
  db:
    image: mysql:latest
    env_file:
      - .env
    networks:
      - drive

  bot:
    build:
      context: .
      dockerfile: ./docker/bot.dockerfile
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - drive
    volumes:
      - project:/app

networks:
  drive:


volumes:
  project:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./
