# syntax=docker/dockerfile:1

FROM node:18-alpine

WORKDIR /app

RUN --mount=type=secret,id=env,--target=

COPY . .

RUN yarn install
RUN yarn build

# RUN yarn knex migrate:latest --env prod
RUN yarn prestart

CMD [ "yarn", "start" ]
