# syntax=docker/dockerfile:1

FROM node:18-alpine

RUN apk add --no-cache --upgrade bash

RUN npm install -g pm2

WORKDIR /app

COPY . .

RUN chmod +x ./docker/env_util.sh
RUN /bin/sh -c ./docker/env_util.sh

RUN yarn install
RUN yarn build

# RUN yarn knex migrate:latest --env prod
RUN yarn prestart

EXPOSE 80

CMD [ "pm2-runtime", "start", "ecosystem.config.js" ]
